### PR TITLE
Coding standards

### PR DESCRIPTION
**Pull request by tareiking**
@dashaluna definitely encouraged my to fix up those spaces.. Better?

### CODE REVIEW

**Comment by dashaluna** [comment]
@tareiking Shhhhweet :) Missed couple:
- https://github.com/tareiking/fontawesome-icon-chooser/blob/master/tinymce-fontawesome.php#L61
- https://github.com/tareiking/fontawesome-icon-chooser/blob/master/tinymce-fontawesome.php#L90
- https://github.com/tareiking/fontawesome-icon-chooser/blob/master/tinymce-fontawesome.php#L101

**Comment by tareiking** [comment]
Thanks ya'll, @dashaluna great spot on `===` :grinning: 

@dashaluna Maybe its because I'm in an airport or I'm blind, but what spaces are missing here? : 

https://github.com/tareiking/fontawesome-icon-chooser/blob/master/tinymce-fontawesome.php#L61
https://github.com/tareiking/fontawesome-icon-chooser/blob/master/tinymce-fontawesome.php#L90
https://github.com/tareiking/fontawesome-icon-chooser/blob/master/tinymce-fontawesome.php#L101

**Comment by dashaluna** [comment]
@tareiking `function init_buttons( $buttons ){` should be `function init_buttons( $buttons ) {` the **){** :)

**Comment by tareiking** [comment]
@dashaluna As an added bonus, it looks like my codesniffer plugin settings might be what's causing me to miss the additional spacing issues you identified, so thanks again :)

**Comment by dashaluna** [comment]
No worries :) Glad to help

**Pull request merged**
